[files]
extend-exclude = [
"*.yaml",
"*.yml",
"*.md",
"*.sh",
"*.tpl",
"go.mod",
"go.sum",
"tests/",
"api/",
]
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true

[default]
locale = "en"
extend-glob = []
extend-ignore-identifiers = []
extend-ignore-words-re = []
extend-ignore-re = []

[default.extend-identifiers]
cann_version = "cann_version"
CannVersion = "CannVersion"
Encrypter = "Encrypter"
NotificatonWeb = "NotificatonWeb"
Mininum = "Mininum"
cannVersion = "cannVersion"